# Generated by Django 3.1.4 on 2024-03-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchagemaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=200, null=True)),
                ('purchage_date', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
