# Generated by Django 3.1.4 on 2024-03-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0004_auto_20240307_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchagemaster',
            name='gst',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='purchagemaster',
            name='item',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='purchagemaster',
            name='qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchagemaster',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchagemaster',
            name='unit_text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
