# Generated by Django 5.0.3 on 2024-03-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nursery", "0009_partylistfinalmaster"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartylistdeleteMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_no", models.CharField(max_length=200, null=True)),
                ("farmer_name", models.CharField(max_length=200, null=True)),
                ("seed_name", models.CharField(max_length=200, null=True)),
                ("address", models.CharField(max_length=200, null=True)),
                ("qty", models.IntegerField(blank=True, null=True)),
                ("price", models.IntegerField(blank=True, null=True)),
                ("advn", models.IntegerField(blank=True, null=True)),
                ("tprice", models.IntegerField(blank=True, null=True)),
                ("seed_date", models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
