# Generated by Django 5.0.3 on 2024-03-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nursery", "0013_pbsugarcanemaster"),
    ]

    operations = [
        migrations.AddField(
            model_name="pbsugarcanemaster",
            name="advance",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pbsugarcanemaster",
            name="bill_no",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="pbsugarcanemaster",
            name="item",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="pbsugarcanemaster",
            name="price",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pbsugarcanemaster",
            name="total_price",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pbsugarcanemaster",
            name="vehicle_no",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="pbsugarcanemaster",
            name="vehicle_weight",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pbsugarcanemaster",
            name="verity_no",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="pbsugarcanemaster",
            name="weibrage_weight",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
