# Generated by Django 5.0.3 on 2024-03-22 07:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "nursery",
            "0014_pbsugarcanemaster_advance_pbsugarcanemaster_bill_no_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="pbsugarcanemaster",
            old_name="nurser_date",
            new_name="nursery_date",
        ),
    ]
