# Generated by Django 5.0.3 on 2024-03-26 07:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nursery", "0015_rename_nurser_date_pbsugarcanemaster_nursery_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pbledgermaster",
            old_name="nurser_date",
            new_name="nursery_date",
        ),
    ]
