# Generated by Django 5.0.3 on 2024-04-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nursery", "0018_sbcustomermaster"),
    ]

    operations = [
        migrations.CreateModel(
            name="SbsugarcaneMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200, null=True)),
                ("bill_no", models.CharField(max_length=200, null=True)),
                ("farmer_name", models.CharField(max_length=200, null=True)),
                ("nursery_date", models.CharField(max_length=200, null=True)),
                ("address", models.CharField(max_length=200, null=True)),
                ("mobile_num", models.IntegerField(blank=True, null=True)),
                ("verity_no", models.CharField(max_length=200, null=True)),
                ("seedling_no", models.CharField(max_length=200, null=True)),
                ("price", models.IntegerField(blank=True, null=True)),
                ("advance", models.IntegerField(blank=True, null=True)),
                ("total_price", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
