# Generated by Django 5.0.3 on 2024-04-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nursery", "0019_sbsugarcanemaster"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabourMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("farmer_name", models.CharField(max_length=200, null=True)),
                ("address", models.CharField(max_length=200, null=True)),
                ("mobile_num", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
