# Generated by Django 5.0.3 on 2024-04-18 06:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nursery", "0021_rename_sbsugarcanemaster_sbsugarmaster"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sbsugarmaster",
            old_name="seedling_no",
            new_name="seedlings_no",
        ),
    ]
