# Generated by Django 5.0.3 on 2024-04-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nursery", "0022_rename_seedling_no_sbsugarmaster_seedlings_no"),
    ]

    operations = [
        migrations.CreateModel(
            name="sclabourMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_no", models.CharField(max_length=200, null=True)),
                ("labour_name", models.CharField(max_length=200, null=True)),
                ("address", models.CharField(max_length=200, null=True)),
                ("mobile_num", models.IntegerField(blank=True, null=True)),
                ("description", models.CharField(max_length=200, null=True)),
                ("vehicle_no", models.CharField(max_length=200, null=True)),
                ("cane_weight", models.IntegerField(blank=True, null=True)),
                ("price", models.IntegerField(blank=True, null=True)),
                ("total_price", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
