# Generated by Django 5.0.3 on 2024-04-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nursery", "0024_incustomermaster"),
    ]

    operations = [
        migrations.CreateModel(
            name="incustMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("farmer_name", models.CharField(max_length=200, null=True)),
                ("factory", models.CharField(max_length=200, null=True)),
                ("address", models.CharField(max_length=200, null=True)),
                ("mobile_num", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="incustomerMaster",
        ),
    ]
