# Generated by Django 5.0.3 on 2024-04-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nursery", "0025_incustmaster_delete_incustomermaster"),
    ]

    operations = [
        migrations.CreateModel(
            name="inlistMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_no", models.CharField(max_length=200, null=True)),
                ("factory", models.CharField(max_length=200, null=True)),
                ("address", models.CharField(max_length=200, null=True)),
                ("mobile_num", models.CharField(max_length=200, null=True)),
                ("place", models.CharField(max_length=200, null=True)),
                ("circle", models.CharField(max_length=200, null=True)),
                ("field_name", models.CharField(max_length=200, null=True)),
                ("field_num", models.CharField(max_length=200, null=True)),
                ("farmer", models.CharField(max_length=200, null=True)),
                ("description", models.CharField(max_length=200, null=True)),
                ("indent_no", models.CharField(max_length=200, null=True)),
                ("verity_code", models.CharField(max_length=200, null=True)),
                ("seedlings_no", models.CharField(max_length=200, null=True)),
                ("price", models.CharField(max_length=200, null=True)),
                ("total_price", models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
