# Generated by Django 5.0.3 on 2024-04-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nursery", "0026_inlistmaster"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inlistmaster",
            name="bill_no",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inlistmaster",
            name="mobile_num",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inlistmaster",
            name="price",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inlistmaster",
            name="total_price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
