# Generated by Django 5.0.3 on 2024-04-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nursery", "0027_alter_inlistmaster_bill_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inlistmaster",
            name="field_num",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
