# Generated by Django 5.0.6 on 2024-05-27 08:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nursery", "0028_alter_inlistmaster_field_num"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PartylistfinalMaster",
        ),
    ]
